name: Power outage Toot workflow

on:
  workflow_dispatch:
  schedule:
     - cron: "30 * * * *"

jobs:
  toot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies 
        run: |-
          cd /home/runner/work/california_power_outage/california_power_outage
          pip3 install Mastodon.py
          python3 -m pip install --upgrade Pillow

      - name: Post fire title and map into Mastodon
        run: |-
          cd /home/runner/work/california_power_outage/california_power_outage
          python3 toot.py
        env:
          MASTODON_EMAIL: ${{ secrets.MASTODON_EMAIL }}
          MASTODON_PASSWORD: ${{ secrets.MASTODON_PASSWORD }}
          MASTODON_SERVER: ${{ secrets.MASTODON_SERVER }}

